version: "3.7"
services:
  tor:
    image: peterdavehello/tor-socks-proxy
    container_name: tor-socks-proxy
    restart: always
    healthcheck:
      test: curl --socks5-hostname 127.0.0.1:9150 https://ipinfo.tw/ip
      interval: 10s
      start_period: 30s
    networks:
      - app-network
    ports:
      - 9150:9150

  node:
    env_file: .env
    build:
      network: host
      context: .
      dockerfile: Dockerfile
      args:
        DB_HOST: ${TOKEN}
        PORT: ${PORT}
    ports:
      - "3005:3005"
    networks:
      - app-network
    depends_on:
      tor:
        condition: service_healthy
    volumes:
      - node_modules:/app/node_modules
      - dbdata:/tmp/CHIA/
    tty: true
    restart: unless-stopped
    stdin_open: false

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
  dbdata:
